apiVersion: v1
kind: Service
metadata:
    name: {{ include "service_fullname" }}
    labels:
        app: {{ include "service_fullname" }}
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    clusterIP: None
